language: python
python:
  - 2.7
install:
  - CFLAGS="-O0" pip install lxml
  - pip install flake8 coveralls psycopg2
  # Temporary till nereid get released
  - pip install https://github.com/openlabs/nereid/archive/develop.tar.gz
  - python setup.py install
script:
  - coverage run setup.py test
  - python setup.py test_on_postgres
  - flake8 .
after_success:
  coveralls
notifications:
  email:
  - ci-notify@openlabs.co.in
